Repository siemens/ngx-datatable, pull requests merged in 2021-09, with the labels that each got.

#2 chore(gh-actions): correct gh-pages deployment config
  .github/workflows/test_and_deploy.yml
Labels: enhancement

#3 fix: tabindex on scrollable datatable body
  projects/ngx-datatable/src/lib/components/datatable.component.html
Labels: enhancement

#4 fix: emit page event on page size change for virtual paging
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.ts
Labels: bug

#5 fix: fix CSP script-src 'self'
  projects/ngx-datatable/src/lib/components/footer/pager.component.ts
Labels: bug

#6 fix: fix clearTimeout/_destroySubscription race
  projects/ngx-datatable/src/lib/directives/long-press.directive.ts
Labels: bug

#8 fix: refresh virtual grid after scroll
  projects/ngx-datatable/src/lib/components/body/body.component.ts
Labels: bug

#7 feat: support custom content for empty table
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.html
  projects/ngx-datatable/src/lib/components/datatable.component.ts
Labels: enhancement

#10 Fix/column resize
  projects/ngx-datatable/src/lib/components/datatable.component.html
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/components/header/header.component.ts
  projects/ngx-datatable/src/lib/directives/resizeable.directive.ts
  projects/ngx-datatable/src/lib/themes/bootstrap.scss
  projects/ngx-datatable/src/lib/themes/dark.scss
  projects/ngx-datatable/src/lib/themes/material.scss
  projects/ngx-datatable/src/lib/utils/math.ts
Labels: bug

#11 fix: fix orderable directive
  projects/ngx-datatable/src/lib/directives/orderable.directive.ts
Labels: bug

#14 Docs/copyright readme note
  LICENSE
  README.md
Labels: documentation

#13 Fix/add loading spinner
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.html
  src/app/paging/paging-virtual.component.scss
  src/app/paging/paging-virtual.component.ts
Labels: enhancement
