Repository siemens/ngx-datatable, pull requests merged in 2025-03, with the labels that each got.

#156 refactor: remove unused import
  projects/ngx-datatable/src/lib/components/body/body.component.ts
Labels: enhancement

#153 refactor: use interface for row properties that may be set by the dat…
  projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
Labels: enhancement

#152 fix: allow partial overrides of messages
  projects/ngx-datatable/src/lib/components/datatable.component.html
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/ngx-datatable.module.ts
Labels: bug

#149 refactor: only export symbols that are meant to be exported
  projects/ngx-datatable/src/lib/ngx-datatable.module.ts
  projects/ngx-datatable/src/public-api.ts
Labels: enhancement

#154 refactor: simplify column directive converting
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/utils/column-helper.ts
Labels: enhancement

#158 refactor: always use type event
  projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
  projects/ngx-datatable/src/lib/components/body/selection.component.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
Labels: enhancement

#160 refactor: remove unused loop index
  projects/ngx-datatable/src/lib/components/body/body-row.component.ts
Labels: enhancement

#164 refactor: remove useless cleanup
  projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
Labels: enhancement

#161 fix: only run disabled check on rows
  playwright/e2e/row-disabled.spec.ts
  playwright/snapshots/e2e/row-disabled.spec.ts-snapshots/disabled-chromium-linux.png
  projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
  projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
  projects/ngx-datatable/src/lib/components/body/body-row.component.ts
  projects/ngx-datatable/src/lib/components/body/body.component.spec.ts
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
  src/app/basic/disabled-rows.component.ts
Labels: bug

#167 fix: add missing type to comparator
  projects/ngx-datatable/src/lib/components/columns/column.directive.ts
  projects/ngx-datatable/src/lib/types/table-column.type.ts
Labels: enhancement

#168 refactor: add dedicated type for `SelectEvent`
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/body/selection.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
  src/app/selection/selection-cell.component.ts
  src/app/selection/selection-chkbox-template.component.ts
  src/app/selection/selection-chkbox.component.ts
  src/app/selection/selection-disabled.component.ts
  src/app/selection/selection-multi-click-chkbox.component.ts
  src/app/selection/selection-multi-click.component.ts
  src/app/selection/selection-multi.component.ts
  src/app/selection/selection-single.component.ts
Labels: enhancement

#166 docs: use HttpClient
  src/app/app.module.ts
  src/app/basic/basic-auto.component.ts
  src/app/basic/basic-fixed.component.ts
  src/app/basic/bootstrap.component.ts
  src/app/basic/contextmenu.component.ts
  src/app/basic/css.component.ts
  src/app/basic/dark-theme.component.ts
  src/app/basic/disabled-rows.component.ts
  src/app/basic/dynamic-height.component.ts
  src/app/basic/filter.component.ts
  src/app/basic/footer.component.ts
  src/app/basic/fullscreen.component.ts
  src/app/basic/inline.component.ts
  src/app/basic/live.component.ts
  src/app/basic/responsive.component.ts
  src/app/basic/row-detail.component.ts
  src/app/basic/row-grouping.component.ts
  src/app/basic/rx.component.ts
  src/app/basic/scrolling-dynamically.component.ts
  src/app/basic/scrolling.component.ts
  src/app/basic/tabs.component.ts
  src/app/basic/virtual.component.ts
  src/app/columns/column-flex.component.ts
  src/app/columns/column-force.component.ts
  src/app/columns/column-reorder.component.ts
  src/app/columns/column-standard.component.ts
  src/app/columns/pinning.component.ts
  src/app/data.model.ts
  src/app/data.service.ts
  src/app/drag-drop/drag-drop.component.ts
  src/app/paging/paging-client.component.ts
  src/app/selection/selection-cell.component.ts
  src/app/selection/selection-chkbox-template.component.ts
  src/app/selection/selection-chkbox.component.ts
  src/app/selection/selection-disabled.component.ts
  src/app/selection/selection-multi-click-chkbox.component.ts
  src/app/selection/selection-multi-click.component.ts
  src/app/selection/selection-multi.component.ts
  src/app/selection/selection-single.component.ts
  src/app/sorting/sorting-client.component.ts
  src/app/sorting/sorting-comparator.component.ts
  src/app/sorting/sorting-default.component.ts
  src/app/sorting/sorting-server.component.ts
  src/app/summary/summary-row-custom-template.component.ts
  src/app/summary/summary-row-inline-html.component.ts
  src/app/summary/summary-row-simple.component.ts
  src/app/templates/template-dom.component.ts
  src/app/templates/template-obj.component.ts
  src/app/tree/client-tree.component.ts
  src/app/tree/fullscreen.component.ts
Labels: documentation

#172 docs: add missing type for sorting
  src/app/sorting/sorting-server.component.ts
Labels: documentation

#169 docs: add missing type for server paging
  src/app/paging/paging-scrolling-novirtualization.component.ts
  src/app/paging/paging-server.component.ts
  src/app/summary/summary-row-server-paging.component.ts
Labels: documentation

#175 docs: fix typing of cell class
  src/app/basic/css.component.ts
Labels: documentation

#180 refactor: simplify column in group iteration
  projects/ngx-datatable/src/lib/utils/math.ts
Labels: enhancement

#178 refactor: add missing internal types
  projects/ngx-datatable/src/lib/directives/orderable.directive.ts
  projects/ngx-datatable/src/lib/utils/math.ts
  projects/ngx-datatable/src/lib/utils/sort.ts
  projects/ngx-datatable/src/lib/utils/tree.ts
Labels: enhancement

#176 refactor: adjust the type of rowClass as it is never called with groups
  projects/ngx-datatable/src/lib/components/body/body-row.component.ts
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.ts
Labels: enhancement

#174 feat: add type for context menu event
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
  src/app/basic/contextmenu.component.ts
Labels: enhancement

#177 refactor: simplify total width calculation
  projects/ngx-datatable/src/lib/utils/column.ts
  projects/ngx-datatable/src/lib/utils/math.ts
Labels: enhancement

#170 docs: add missing type for functions
  src/app/basic/css.component.ts
  src/app/basic/dynamic-height.component.ts
  src/app/basic/filter.component.ts
  src/app/basic/responsive.component.ts
  src/app/basic/row-detail.component.ts
  src/app/basic/virtual.component.ts
  src/app/drag-drop/drag-drop.component.ts
  src/app/selection/selection-cell.component.ts
  src/app/selection/selection-chkbox-template.component.ts
  src/app/selection/selection-chkbox.component.ts
  src/app/selection/selection-disabled.component.ts
  src/app/selection/selection-multi-click-chkbox.component.ts
  src/app/selection/selection-multi-click.component.ts
  src/app/selection/selection-multi.component.ts
  src/app/selection/selection-single.component.ts
  src/app/sorting/sorting-comparator.component.ts
  src/app/sorting/sorting-server.component.ts
  src/app/summary/summary-row-server-paging.component.ts
Labels: documentation

#173 feat: add type for details toggle event
  projects/ngx-datatable/src/lib/components/row-detail/row-detail.directive.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
  src/app/basic/responsive.component.ts
  src/app/basic/row-detail.component.ts
Labels: enhancement

#171 docs: add missing type for updateValue functions
  src/app/basic/disabled-rows.component.ts
  src/app/basic/inline.component.ts
  src/app/basic/live.component.ts
  src/app/basic/row-grouping.component.ts
  src/app/basic/scrolling-dynamically.component.ts
  src/app/data.model.ts
Labels: documentation

#185 build: enable noImplicitAny in tsconfig
  projects/ngx-datatable/src/lib/directives/orderable.directive.spec.ts
  projects/ngx-datatable/src/lib/test/jasmine-matchers.ts
  projects/ngx-datatable/src/lib/utils/math.spec.ts
  tsconfig.json
Labels: enhancement

#186 refactor: always use the same event type for reorder columns
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/components/header/header.component.ts
  projects/ngx-datatable/src/lib/directives/orderable.directive.ts
  projects/ngx-datatable/src/lib/types/internal.types.ts
Labels: enhancement

#184 Ci/codeclimate coverage report
  .github/workflows/test_and_deploy.yml
Labels: enhancement

#182 refactor: remove unused code in long-press directive
  projects/ngx-datatable/src/lib/directives/long-press.directive.ts
Labels: enhancement

#163 Refactor/consolidate internal column creation
  projects/ngx-datatable/src/lib/components/body/body-cell.component.spec.ts
  projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
  projects/ngx-datatable/src/lib/components/body/body-row.component.ts
  projects/ngx-datatable/src/lib/components/body/body.component.spec.ts
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/body/ghost-loader/ghost-loader.component.ts
  projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.spec.ts
  projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  projects/ngx-datatable/src/lib/components/header/header-cell.component.ts
  projects/ngx-datatable/src/lib/components/header/header.component.ts
  projects/ngx-datatable/src/lib/directives/draggable.directive.ts
  projects/ngx-datatable/src/lib/directives/long-press.directive.ts
  projects/ngx-datatable/src/lib/directives/orderable.directive.spec.ts
  projects/ngx-datatable/src/lib/directives/orderable.directive.ts
  projects/ngx-datatable/src/lib/types/internal.types.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
  projects/ngx-datatable/src/lib/types/table-column.type.ts
  projects/ngx-datatable/src/lib/utils/column-helper.ts
  projects/ngx-datatable/src/lib/utils/column.ts
  projects/ngx-datatable/src/lib/utils/math.spec.ts
  projects/ngx-datatable/src/lib/utils/math.ts
Labels: enhancement

#188 refactor: remove implicit this from tree grouping
  projects/ngx-datatable/src/lib/utils/tree.ts
Labels: enhancement

#191 refactor: avoid redundant value lookup in map
  projects/ngx-datatable/src/lib/components/datatable.component.ts
Labels: enhancement

#190 refactor: reflect in type that messages and cssClasses configs are al…
  projects/ngx-datatable/src/lib/components/datatable.component.ts
Labels: enhancement

#194 build: remove browserlist
  .browserslistrc
Labels: enhancement

#198 refactor: move footer styles to a component level
  projects/ngx-datatable/src/lib/components/datatable.component.scss
  projects/ngx-datatable/src/lib/components/footer/footer.component.scss
  projects/ngx-datatable/src/lib/components/footer/footer.component.ts
  projects/ngx-datatable/src/lib/components/footer/pager.component.scss
  projects/ngx-datatable/src/lib/components/footer/pager.component.ts
Labels: enhancement

#195 refactor: replace useless subject
  projects/ngx-datatable/src/lib/components/datatable.component.html
  projects/ngx-datatable/src/lib/components/datatable.component.ts
Labels: enhancement

#197 docs: migrate examples to standalone
  src/app/app.module.ts
  src/app/basic/basic-auto.component.ts
  src/app/basic/basic-fixed.component.ts
  src/app/basic/bootstrap.component.ts
  src/app/basic/contextmenu.component.ts
  src/app/basic/css.component.ts
  src/app/basic/dark-theme.component.ts
  src/app/basic/disabled-rows.component.ts
  src/app/basic/dynamic-height.component.ts
  src/app/basic/empty.component.ts
  src/app/basic/filter.component.ts
  src/app/basic/footer.component.ts
  src/app/basic/fullscreen.component.ts
  src/app/basic/inline.component.ts
  src/app/basic/live.component.ts
  src/app/basic/multiple.component.ts
  src/app/basic/responsive.component.ts
  src/app/basic/row-detail.component.ts
  src/app/basic/row-grouping.component.ts
  src/app/basic/rx.component.ts
  src/app/basic/scrolling-dynamically.component.ts
  src/app/basic/scrolling.component.ts
  src/app/basic/tabs.component.ts
  src/app/basic/virtual.component.ts
  src/app/columns/column-flex.component.ts
  src/app/columns/column-force.component.ts
  src/app/columns/column-reorder.component.ts
  src/app/columns/column-standard.component.ts
  src/app/columns/column-toggle.component.ts
  src/app/columns/pinning.component.ts
  src/app/drag-drop/drag-drop.component.ts
  src/app/paging/paging-client.component.ts
  src/app/paging/paging-scrolling-novirtualization.component.ts
  src/app/paging/paging-server.component.ts
  src/app/paging/paging-virtual.component.ts
  src/app/paging/scrolling-server.component.ts
  src/app/selection/selection-cell.component.ts
  src/app/selection/selection-chkbox-template.component.ts
  src/app/selection/selection-chkbox.component.ts
  src/app/selection/selection-disabled.component.ts
  src/app/selection/selection-multi-click-chkbox.component.ts
  src/app/selection/selection-multi-click.component.ts
  src/app/selection/selection-multi.component.ts
  src/app/selection/selection-single.component.ts
  src/app/sorting/sorting-client.component.ts
  src/app/sorting/sorting-comparator.component.ts
  src/app/sorting/sorting-default.component.ts
  src/app/sorting/sorting-server.component.ts
  src/app/summary/summary-row-custom-template.component.ts
  src/app/summary/summary-row-inline-html.component.ts
  src/app/summary/summary-row-server-paging.component.ts
  src/app/summary/summary-row-simple.component.ts
  src/app/templates/template-dom.component.ts
  src/app/templates/template-obj.component.ts
  src/app/tree/client-tree.component.ts
  src/app/tree/fullscreen.component.ts
Labels: documentation

#200 docs: bootstrap application in a standalone way
  src/app/app.component.ts
  src/app/app.module.ts
  src/main.ts
Labels: documentation

#201 docs: lazy load examples
  src/app/app-routing.module.ts
  src/main.ts
Labels: documentation

#111 fix: apply even/odd classes correctly when rows are grouped
  projects/ngx-datatable/src/lib/components/body/body-cell.component.ts
  projects/ngx-datatable/src/lib/components/body/body-row.component.spec.ts
  projects/ngx-datatable/src/lib/components/body/body-row.component.ts
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
  projects/ngx-datatable/src/lib/types/internal.types.ts
  projects/ngx-datatable/src/lib/types/public.types.ts
Labels: bug

#196 refactor: remove limit from page event
  projects/ngx-datatable/src/lib/types/public.types.ts
  src/app/paging/paging-virtual.component.ts
Labels: enhancement

#202 refactor: move body styles to component level
  projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.scss
  projects/ngx-datatable/src/lib/components/body/body-row-wrapper.component.ts
  projects/ngx-datatable/src/lib/components/body/body-row.component.scss
  projects/ngx-datatable/src/lib/components/body/body-row.component.ts
  projects/ngx-datatable/src/lib/components/body/body.component.scss
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.scss
Labels: enhancement

#205 refactor: simplify tree construction
  playwright/e2e/tree.spec.ts
  playwright/snapshots/e2e/tree.spec.ts-snapshots/client-tree--client-tree-chromium-linux.png
  playwright/snapshots/e2e/tree.spec.ts-snapshots/fullscreen-tree--fullscreen-tree-chromium-linux.png
  projects/ngx-datatable/src/lib/utils/tree.ts
Labels: enhancement

#203 refactor: move fixed-header styles to component level
  projects/ngx-datatable/src/lib/components/datatable.component.scss
  projects/ngx-datatable/src/lib/components/header/header-cell.component.scss
  projects/ngx-datatable/src/lib/components/header/header.component.scss
Labels: enhancement

#204 refactor: make column resize handling typesafe
  projects/ngx-datatable/src/lib/components/datatable.component.ts
Labels: enhancement

#209 refactor: remove custom test matchers
  projects/ngx-datatable/src/lib/components/footer/footer.component.spec.ts
  projects/ngx-datatable/src/lib/test/index.ts
  projects/ngx-datatable/src/lib/test/jasmine-matchers.d.ts
  projects/ngx-datatable/src/lib/test/jasmine-matchers.ts
Labels: enhancement

#214 fix: remove unwanted space below the rows
  playwright/snapshots/e2e/custom-template.spec.ts-snapshots/custom-template-summary--custom-template-default-chromium-linux.png
  playwright/snapshots/e2e/custom-template.spec.ts-snapshots/inline-html-summary--custom-template-lastname-only-chromium-linux.png
  playwright/snapshots/e2e/custom-template.spec.ts-snapshots/simple-summary--no-summary-row-chromium-linux.png
  playwright/snapshots/e2e/custom-template.spec.ts-snapshots/simple-summary--show-summary-row-chromium-linux.png
  playwright/snapshots/e2e/custom-template.spec.ts-snapshots/simple-summary--summary-row-at-bottom-chromium-linux.png
  playwright/snapshots/e2e/custom-template.spec.ts-snapshots/simple-summary--summary-row-at-top-chromium-linux.png
  playwright/snapshots/e2e/filter.spec.ts-snapshots/filter--filtered-chromium-linux.png
  playwright/snapshots/e2e/filter.spec.ts-snapshots/filter--next-page-chromium-linux.png
  playwright/snapshots/e2e/filter.spec.ts-snapshots/filter-chromium-linux.png
  playwright/snapshots/e2e/paging.spec.ts-snapshots/client-paging--default-paginator-chromium-linux.png
  playwright/snapshots/e2e/paging.spec.ts-snapshots/server-paging--server-side-paginator-chromium-linux.png
  playwright/snapshots/e2e/paging.spec.ts-snapshots/server-scrolling--infinite-scroll-after-scroll-chromium-linux.png
  playwright/snapshots/e2e/paging.spec.ts-snapshots/virtual-paging--paginator-chromium-linux.png
  playwright/snapshots/e2e/resize.spec.ts-snapshots/pinning--pinning-name-and-state-column-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/chkbox-selection--checkbox-selection-all-checked-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/chkbox-selection--checkbox-selection-uncheck-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/multi-click-chkbox-selection--backward-navigation-shift-tab-space-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/multi-click-chkbox-selection--navigation-using-tab-and-space-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/multi-click-selection--click-selection-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/multi-selection--using-ctrl-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/multi-selection--using-shift-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/multidisable-selection--disable-row-selection-chromium-linux.png
  playwright/snapshots/e2e/selection.spec.ts-snapshots/single-selection--row-selection-initial-chromium-linux.png
  playwright/snapshots/e2e/tree.spec.ts-snapshots/client-tree--client-tree-chromium-linux.png
  projects/ngx-datatable/src/lib/components/body/body.component.scss
Labels: bug

#215 Ci/GitHub action update
  .github/workflows/test_and_deploy.yml
Labels: enhancement

#211 refactor: move horizontal scroll styles to respective components
  projects/ngx-datatable/src/lib/components/body/body.component.scss
  projects/ngx-datatable/src/lib/components/datatable.component.scss
Labels: enhancement

#192 refactor: ensure that rows are always defined internally
  projects/ngx-datatable/src/lib/components/body/body.component.ts
  projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.spec.ts
  projects/ngx-datatable/src/lib/components/body/summary/summary-row.component.ts
  projects/ngx-datatable/src/lib/components/datatable.component.ts
  src/app/paging/paging-virtual.component.ts
Labels: enhancement

#217 refactor: remove unused styles
  projects/ngx-datatable/src/lib/components/datatable.component.scss
  projects/ngx-datatable/src/lib/themes/material.scss
Labels: enhancement
